server:
  port: 8081

spring:
  cloud:
    gateway:
      routes:
      - id: userModule
        uri: http://localhost:8082/
        predicates:
        - Path=/user/**
      - id: deptModule
        uri: http://localhost:8083/
        predicates:
        - Path=/dept/**